### PR TITLE
Add container to align the menu

### PR DESCRIPTION
**Pull request by nandes2062**
Add container to align the menu with the content of the page

### CODE REVIEW

**Comment by MacGyer** [comment]
@nandes2062 Is there any reason why this should be generally included in the extension?

All markup generation tries to comply with the official Materialize markup.

**Comment by nandes2062** [comment]
It is an option to correctly align the contents of the page with the container
enter image description here

**Comment by MacGyer** [comment]
@nandes2062 why don't you add the class via the $options?

**Comment by nandes2062** [comment]
When using .container in navbar options, does not fit correctly,
enter image description here
  NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options'=>['class'=>'container'],
    ]);
-----------------
On the other hand breadcrumbs if set correctly with options.

**Comment by MacGyer** [comment]
`Html::addCssClass($this->wrapperOptions, 'nav-wrapper container');`

This is your PR change. So why dont you just apply it?

`
NavBar::begin([
  'brandLabel' => 'My Company',
  'brandUrl' => Yii::$app->homeUrl,
  'wrapperOptions'=>['class'=>'container'],
]);
`

That should do the trick.

**Comment by nandes2062** [comment]
great, Thank you.

**Comment by MacGyer** [comment]
You're welcome... have fun.

**Pull request closed without merging**
